server:
  port: 8761
#http://192.168.61.190:8761/ 
spring:
  application:
    name: eurekaservice
    #test
    #test22
    #test33
    #test44
    #test55
    #test66
    
eureka:
  client:
    register-with-eureka : false
    fetch-registry: false


