server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://192.168.61.252:8761/eureka # 회사 내꺼
      defaultZone: {ip.eureka}

spring:
  application:
    name: apigateway-service
  config:
    import: classpath:/bootstrap.yml
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allow-credentials: false
            allowedHeaders: '*'
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS
      routes:
        - id: first-service
          uri: lb://MY-FIRST-SERVICE
          predicates:
            - Path=/first-service/**
          filters:
            #  - AddRequestHeader=first-request, first-request-header2124214214
            #  - AddResponseHeader=first-response, first-response-header2
            - CustomFilter
        - id: second-service
          uri : lb://MY-SECOND-SERVICE
          predicates:
            - Path=/second-service/**
          filters:
            #  - AddRequestHeader=second-request, second-request-header2
            #  - AddResponseHeader=second-response, second-response-header2
            - CustomFilter
        - id: ewallet
          uri: lb://EWALLET-SERVICE
          predicates:
            - Path=/ewallet-service/**
          filters:
            - RewritePath=/ewallet-service/(?<segment>.*), /$\{segment}
            #  - AddRequestHeader=second-request, second-request-header2
            #  - AddResponseHeader=second-response, second-response-header2
            - CustomFilter
######  USER START  ##############################################
#        - id: user
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/user-service/**
#            - Method=GET,POST
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/join
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/health-check
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: user
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/actuator/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/dd, /user-service/hello, /user-service/h2-console
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
######  USER END  ##############################################
        - id: remit
          uri: lb://REMIT-SERVICE
          predicates:
            - Path=/remit/**
          filters:
            #  - AddRequestHeader=second-request, second-request-header2
            #  - AddResponseHeader=second-response, second-response-header2
            - CustomFilter
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment-service/**
          filters:
            #  - AddRequestHeader=second-request, second-request-header2
            #  - AddResponseHeader=second-response, second-response-header2
            - CustomFilter
        - id: chargehistory-service
          uri: lb://CHARGEHISTORY-SERVICE
          predicates:
            - Path=/chargehistory-service/**
          filters:
            #  - AddRequestHeader=second-request, second-request-header2
            #  - AddResponseHeader=second-response, second-response-header2
            - CustomFilter

management:
  endpoints:
    web:
      exposure:
        include: info, refresh, health, beans, httpexchanges
