server:
  port: 8888

spring:
  application:
    name: configservice
  profiles:
    active: native
#    active: git
  cloud:
    config:
      server:
        native:
          search-locations: ./
        git:
          uri: https://github.com/KBDS-TD/E-Wallet-Config.git
